"""
scraper/email_brevo.py
======================
Sends digest emails via the Brevo (formerly Sendinblue) transactional email API.
Free tier: 300 emails/day, no credit card required.

Requires:
  BREVO_API_KEY environment variable (set as a GitHub Secret)
  BREVO_SENDER_EMAIL environment variable (the verified sender address in Brevo)
  BREVO_SENDER_NAME  environment variable (optional, defaults to "Naylor Content Digests")
"""

import os
import json
import re
import logging
import requests
from datetime import datetime


BREVO_API_URL = "https://api.brevo.com/v3/smtp/email"


def send_digest(to_address: str, newsletter_name: str, digest_text: str) -> tuple[bool, str]:
    """Send a formatted digest email via Brevo. Returns (success, message)."""
    api_key     = os.environ.get("BREVO_API_KEY", "")
    sender_email = os.environ.get("BREVO_SENDER_EMAIL", "hananiel91@gmail.com")
    sender_name  = os.environ.get("BREVO_SENDER_NAME", "Naylor Content Digests")

    if not api_key:
        return False, "BREVO_API_KEY environment variable not set."

    subject = (
        f"Content Digest — {newsletter_name} — "
        f"{datetime.utcnow().strftime('%B %-d, %Y')}"
    )

    payload = {
        "sender":    {"name": sender_name, "email": sender_email},
        "to":        [{"email": to_address}],
        "subject":   subject,
        "htmlContent": _to_html(digest_text, newsletter_name),
        "textContent": digest_text,
    }

    headers = {
        "accept":       "application/json",
        "content-type": "application/json",
        "api-key":      api_key,
    }

    try:
        resp = requests.post(BREVO_API_URL, headers=headers,
                             data=json.dumps(payload), timeout=30)
        resp.raise_for_status()
        logging.info(f"Digest sent to {to_address} for '{newsletter_name}'")
        return True, f"Sent via Brevo (messageId: {resp.json().get('messageId','')})"
    except requests.exceptions.HTTPError as e:
        msg = f"Brevo error {e.response.status_code}: {e.response.text[:200]}"
        logging.error(msg)
        return False, msg
    except Exception as e:
        logging.error(f"Email send failed: {e}")
        return False, str(e)


def _to_html(plain: str, name: str) -> str:
    """Convert plain-text digest to a clean HTML email."""
    lines = plain.split("\n")
    parts = [
        "<html><body style='font-family:Arial,sans-serif;max-width:660px;"
        "margin:0 auto;color:#333;padding:20px 0'>",
        f"<div style='background:#1D9E75;padding:20px 24px;border-radius:6px 6px 0 0'>",
        f"<p style='color:#fff;font-size:13px;margin:0 0 4px'>Naylor Newsletter Content System</p>",
        f"<h1 style='color:#fff;font-size:20px;margin:0'>{name}</h1>",
        "</div>",
        "<div style='border:1px solid #e0e0e0;border-top:none;border-radius:0 0 6px 6px;"
        "padding:20px 24px'>",
    ]

    i = 0
    while i < len(lines):
        line = lines[i].strip()
        m = re.match(r'^(\d+)\.\s+(.+)$', line)
        if m:
            num, title = m.group(1), m.group(2)
            summary_raw = lines[i+1].strip() if i+1 < len(lines) else ""
            url_line    = lines[i+2].strip() if i+2 < len(lines) else ""
            summary     = re.sub(r'\s*\(_[^)]+_\)\s*$', '', summary_raw)
            src_m       = re.search(r'\(_([^)]+)_\)', summary_raw)
            source      = src_m.group(1) if src_m else ""
            parts.append(
                f"<div style='margin:0 0 18px;padding:14px 16px;"
                f"border-left:3px solid #1D9E75;background:#f9faf9;border-radius:3px'>"
                f"<p style='margin:0 0 5px;font-weight:bold;font-size:14px'>{num}. {title}</p>"
                f"<p style='margin:0 0 8px;font-size:13px;color:#444;line-height:1.5'>{summary}</p>"
            )
            if url_line.startswith("http"):
                parts.append(
                    f"<a href='{url_line}' style='font-size:12px;color:#1D9E75;text-decoration:none'>"
                    f"Read article{' — ' + source if source else ''} &rarr;</a>"
                )
            parts.append("</div>")
            i += 3
            continue

        if line.startswith("===") or line.startswith("───"):
            i += 1
            continue

        if ":" in line and not line.startswith("http") and 5 < len(line) < 80:
            parts.append(f"<p style='font-size:12px;color:#999;margin:2px 0'>{line}</p>")

        i += 1

    parts.append(
        "<p style='font-size:11px;color:#bbb;margin-top:24px;padding-top:12px;"
        "border-top:1px solid #eee'>Generated by the Naylor Newsletter Content System</p>"
        "</div></body></html>"
    )
    return "\n".join(parts)
